# Generated by Django 4.2.8 on 2023-12-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_orderdetails_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='username',
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer'),
        ),
    ]
