# Generated by Django 4.2.8 on 2023-12-14 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_orderdetails_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_details', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.orderdetails')),
                ('product', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.products')),
            ],
        ),
    ]
