# Generated by Django 4.2.8 on 2023-12-14 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_products_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='order_details',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.orderdetails'),
        ),
    ]
